  spring:
      datasource:
          url: jbc:h2:testdb
          username: root
          password: toor
          driverClassName: org.h2.Driver
      jpa:
          database: h2
          database-plataform: org.hibernate.dialect.H2Dialect
          # utilizar apenas para desenvolvimento
          defer-datasource-initialization: true
          hibernate:
              ddl-auto: create-drop
      h2:
          console:
              enabled: true
